



development:
  adapter: postgresql
  encoding: unicode
  database: airbnb_clone_development
  host: localhost
  pool: 5
  username: postgres
  password: postgres




test:
  adapter: postgresql
  encoding: unicode
  database: airbnb_clone_test
  host: localhost
  pool: 5
  username: postgres
  password: postgres